sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '6'
before_install:
- npm i -g npm@^3.0.0
before_script:
- npm prune
script:
- npm run verify
after_success:
- npm run publish-coverage-report
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
addons:
  browserstack:
    username: jan.molak@smartcodeltd.co.uk
    access_key:
      secure: wW/joCUvC0DyVQfpp40ExJtxJCyuEyzY2+LqmdzJIDKOO+DtbsBCLgrCjseq+tb3kMNC6VcpoD/iIqjK3NHP19lgnPEEZeXdHvK5RhGp4GzzXMbbEHNmT+yfwPMCBH8qG7zNg6wmlfA4N9j8OnC4EHCcIk9+E5++uKp1/kakhqmZ6IJORNgnl2ZT+Fn7nYat0VLyh7GtDAeiJSfD0lFYrqkt0VIEbEmPlnk8viOT2ci/uQXvoSG8Hj4y2vA2ieA2JGJ0mmhvhM0iGjUYloCeBAz2Q19VgOi+RXZDdiTJqmuBFKuAHhi0EJoHLr6QdUE+XhKnBxIAEpm/uM166V/qj20Rd5QBIlCg7xSknceynxWmuZqJaXDPE5yoMcqnAZ1V/TC0PJDQxdxSEhflVAC2HXXBuD5UibKFqN0GXOOENSuinFFCf1OahxR6odaY81V+S6qOUrXWENmWd34I88z9DrEbrvYYIK5B6xTe8yJlGiTrCbOIiy7RiElqbM7JdfgLQ4ixbC+GyUrGVR9LFaoPca8Mmgp/+tHtpQZTQkWlbQMK6aLN0QO178c9AA6dhSOMes0fSqIuvTyoY6YdfXOEoI4jG0i/Vre+dnVLUsjbWx039+rwQSvQprT4h4JtYQLOmLAvD4R18TuBVbCYKGKfukNv5P4ZrHIxOd2gQBfzMvo=
env:
  global:
  - BROWSERSTACK_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BROWSERSTACK_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: qMjR3TgxXurBdHPzW3KcJJKonohXE2v10TxFFHg+Ur0kwH3Zewf7qs4okgPqrAxlHMqMT3sE8XHM6S83uebDMLUpjRSiPP07LjfNJx3iln6PeNUfg5YtOm7c1ryTaue1of4T/4CFuKWRiFPWRcaee62aUWcMORHOgMXhYaT8VIuxqLIm1v+RpHfSw9aJYNKebqh68iyQqBtjpCFu7yDFyHXN770Sbqetr4XuGnCU+8bRwf7jC+lBye+iyu9TAH89Z2tvH4cAX313BOjl1ZqQNuuSSP73FgU6bKA1exzFwrJkbf1T3jPLpSca8R9OukttOXUXMyDwCjtK9RTV9u4UtBAF31FIPLJ99ZTlVkhvZwJpNgFZxtHFXykUB4u/OKoKEeBqS1yZIwOxE4baGLRQ+yKwvxcQj5188FjTyVVJol421hFHC5noRL2IlRd4/5ILeoVIiFVq8hAErHaQaFepLsnxk3urd8mXsFId4VEUjFxqRdE0LI7wv1msHpznyQ0IpkUe7JxLZBTuhyiM6DQfSUowNEo89KzlvBo7zXqhFK6hDQ16/eH6BIYJGg3q+bbr+KhfJLZboBBr51yqicNk7EZK5qCJE/kAhtgAeQyxaXilUIFJXis6ylauRuMbkAa0FjQwKbXoOujoCe1NGumoPtqbfAQbP74KhWcJboxtJxI=
  - secure: OEIehbi2kPjfNp51pr+AkhDVM8yOZEPEdXYrov2K82XUMcP3Qf20WbkXb2yC5bwCUZTxdTN48gHvPdryaeKOk5WMaLz+rwj0eygKn3DSVl4YbIcwM0CbW+/tp8Tcuxp5ZHoozF8WTw3tN9TUE758qyuR2qzzoYjEkOz7ZEXIEacWaKy/HUXxwmzmG2PfIGb7TJg7ZQf3l+NlokyxtOdqxzQ+gCm9oHaTYnePZEJH6jhfZid53heXXMAUf8JzB/ThkrcvsaGZJxrxGiTKfwWHQ+keF0U3wIF7ZDQDP1+CP0Z7rAttDQ3PUYLK3NWZDNVTorLHSxzjJFKJueP4qW8XTg0m3hE1Vj0Lu7dF0mSBncg+uonVSpGsYp5A4McVU7+st9cEWMES+a7hMMI6jMWNBmwMuyy0ZYpXlcA3CLgM8Mhk6eTthAya3W1f+Vq3/4gzF+JqlZ4KsX/8273KPaD7QVS0Aatm8NRAqUDDcP6hD6dmSNlu18WSUWww8MJjgsiUAXl9/TgV9Tqxsf4NqF68TGpebymliAjE5Bgv7LhDjhlQy2ez8N6fasXF0rlg4V4CqjVfn5dPcUTtux+cxpgQS1lUCjV4lGSz6PYJkpYidH+QpeykKQTQh1GnkV+3j8MD87aqQBDB4i9CTTcAqRgWYf5nHP4uRmUB7Suit1KD2yo=
