name: "Main: Detect changes"

on:
  workflow_call:
    inputs:
      fetch-depth:
        description: "Number of commits to fetch. 0 indicates all history for all branches and tags"
        type: number
        required: false
        default: 0
      files:
        description: "Check for changes using only this list of files (Defaults to the entire repo)"
        type: string
        required: false
        default: ""
      files-ignore:
        description: "Ignore changes to this list of files"
        type: string
        required: false
        default: ""

    outputs:
      has_changes:
        description: Returns if any changes to the specified list of files have been detected
        value: ${{ jobs.detect-changes.outputs.has_changes }}

      # From https://github.com/tj-actions/changed-files/blob/main/action.yml
      # Naming and descriptions as per the original implementation
      all_modified_files:
        description: List of all copied, modified, added and deleted files.
        value: ${{ jobs.detect-changes.outputs.all_modified_files }}
      only_modified:
        description: Return true when all files provided using the files input have been modified.
        value: ${{ jobs.detect-changes.outputs.only_modified }}
      any_changed:
        description: Return true only when any files provided using the files input have changed.
        value: ${{ jobs.detect-changes.outputs.any_changed }}

permissions:
  contents: read

jobs:
  detect-changes:
    runs-on:  ubuntu-latest
    outputs:
      has_changes: ${{ steps.changed-files.outputs.any_changed }}
      only_modified: ${{ steps.changed-files.outputs.only_modified }}
      all_modified_files: ${{ steps.changed-files.outputs.all_modified_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@7ecfc6730dff8072d1cc5215a24cc9478f55264d # v35.8.0
        with:
          files: ${{ inputs.files }}
          files_ignore: ${{ inputs.files-ignore }}
          since_last_remote_commit: true

      - name: Summary (no changes)
        if: steps.changed-files.outputs.any_changed == 'false'
        run: |
          echo "No changes detected" >> $GITHUB_STEP_SUMMARY

      - name: Summary (changes detected)
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "- $file" >> $GITHUB_STEP_SUMMARY
          done
